services:
# ZABBIX SERVER

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server-pgsql
    environment:
      - DB_SERVER_HOST=database-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Stefanini@20
      - ZBX_STARTPOLLERS=20
      - ZBX_STARTPOLLERSUNREACHABLE=5
      - ZBX_CACHESIZE=1G
      - ZBX_STARTHISTORYPOLLERS=5
      - ZBX_STARTHTTPPOLLERS=5
      - ZBX_STARTODBCPOLLERS=5
      - ZBX_STARTPROXYPOLLERS=5
      - ZBX_STARTBROWSERPOLLERS=5
      - ZBX_TIMEOUT= 30
      - ZBX_STARTTIMERS=5
      - ZBX_STARTLLDPROCESSORS=2
      - ZBX_STARTESCALATORS=5
      - ZBX_HOUSEKEEPINGFREQUENCY=1
      - ZBX_MAXHOUSEKEEPERDELETE=5000
      - ZBX_PROBLEMHOUSEKEEPINGFREQUENCY=60
      - ZBX_STARTPOLLERS=5
      - ZBX_STARTPREPROCESSORS=3 
      - ZBX_STARTCONNECTORS=1
      - ZBX_STARTPOLLERSUNREACHABLE=1
      - ZBX_STARTTRAPPERS=5
      - ZBX_STARTPINGERS=1
      - ZBX_STARTREPORTWRITERS=3
      - ZBX_WEBSERVICEURL=http://zabbix-web-service:10053/report 
      - ZBX_STARTIPMIPOLLERS=1
      - ZBX_ENABLE_SNMP_TRAPS=true
      - ZBX_STARTVMWARECOLLECTORS=1
      - ZBX_VMWAREFREQUENCY=60
      - ZBX_VMWAREPERFFREQUENCY=60
      - ZBX_VMWARECACHESIZE=8M
      - ZBX_VMWARETIMEOUT=10
      - ZBX_STARTJAVAPOLLERS=1
      - ZBX_ENABLEREMOTECOMMANDS=1


    init: true
    restart: unless-stopped
    networks:
      - zabbix_network

# ZABBIX FRONT

  zabbix-web-apache-pgsql:
    image: zabbix/zabbix-web-apache-pgsql:alpine-7.0-latest
    container_name: zabbix-web-apache-pgsql
    environment:
      - DB_SERVER_HOST=database-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Stefanini@20
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - PHP_TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
      - zabbix_network
    ports:
      - '8080:8080'

# ZABBIX PROXY

  zabbix-proxy-sqlite:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0-latest
    container_name: zabbix-proxy-sqlite
    environment:
      - ZBX_HOSTNAME=zabbix-proxy-sqlite
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - ZBX_TIMEOUT=30
      - ZBX_PROXYMODE=0
      - ZBX_SERVER_PORT=10051
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_PROXYLOCALBUFFER=0
      - ZBX_PROXYOFFLINEBUFFER=1
      - ZBX_STARTIPMIPOLLERS=1
      - ZBX_JAVAGATEWAYPORT=10052
      - ZBX_STARTJAVAPOLLERS=0
      - ZBX_STARTTRAPPERS=5
      - ZBX_STARTVMWARECOLLECTORS=2
      - ZBX_VMWAREFREQUENCY=60
      - ZBX_VMWAREPERFFREQUENCY=60
      - ZBX_VMWARECACHESIZE=32M
      - ZBX_VMWARETIMEOUT=30

    restart: unless-stopped
    ports:
      - '10051:10051'
      - '162:162'
      - '161:161'
    networks:
      - zabbix_network


# ZABBIX AGENT

  zabbix-proxy-agent:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zabbix-agent2
    environment:
      - ZBX_HOSTNAME=zabbix-server-agent
      - ZBX_SERVER_HOST=zabbix-proxy-sqlite
      - ZBX_TIMEOUT=30
    restart: unless-stopped
    networks:
      - zabbix_network  
    ports:
      - '10050:10050'

# ZABBIX REPORT

  zabbix-web-service:
    image: zabbix/zabbix-web-service:alpine-7.0-latest
    container_name: zabbix-web-service
    environment:
      - ZBX_STARTREPORTWRITERS=2
      - ZBX_WEBSERVICEURL="http://zabbix-web-apache-pgsql:10053/report"
      - ZBX_ALLOWEDIP=zabbix-web-apache-pgsql
      - ZBX_LISTENPORT=10053
      - ZBX_TIMEOUT=30
    restart: unless-stopped
    ports:
      - '10053:10053'
    networks:
      - zabbix_network

networks:
  zabbix_network:
    driver: bridge